x-common-env: &cenv
  POSTGRES_PASSWORD: postgres-admin-password
  POSTGRES_USER: postgres
  POSTGRES_DB: payments
  VAULT_TOKEN: vault-root-password
  VAULT_ADDR: http://vault:8200

services:

  postgres:
    image: 'postgres:16'
    environment:
      <<: *cenv
    ports:
      - '5432:5432'

  vault:
    image: hashicorp/vault:latest
    command: |
      vault server -dev -dev-listen-address=0.0.0.0:8200
    environment:
      <<: *cenv
      VAULT_DEV_ROOT_TOKEN_ID: "vault-root-password"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]

  vault-configure:
    image: hashicorp/vault:latest
    restart: no
    command: >
      sh -c "vault secrets enable transit && 
             vault write -force transit/keys/payments &&
             vault write transit/keys/payments/config deletion_allowed=true"
    environment:
      <<: *cenv
    cap_add:
      - IPC_LOCK
    depends_on:
      vault:
        condition: service_healthy